/* ============================================================
   OZKAHYA STUDIO - Turkish / English interface text
   Turkish is the default language. Product translations live in
   js/urunler.js next to the original product information.
   ============================================================ */

const CEVIRILER = {
  tr: {
    homeTitle: "Ozkahya Studio · El Yapımı Gümüş ve Bakır Takı",
    homeDescription: "Ozkahya Studio: gümüş ve bakırdan, tek tek el emeğiyle üretilen kolye, küpe, yüzük, bileklik ve bilezikler.",
    collectionTitle: "Koleksiyon · Ozkahya Studio",
    collectionDescription: "Ozkahya Studio koleksiyonu: el yapımı gümüş ve bakır kolye, küpe, yüzük, bileklik ve bilezikler.",
    logoAlt: "El Yapımı Gümüş ve Bakır",
    homeAria: "Ozkahya Studio ana sayfa",
    menuAria: "Menü",
    languageAria: "Dil seçimi",
    navHome: "Ana Sayfa",
    navCollection: "Koleksiyon",
    navWorkshop: "Atölye",
    navCare: "Bakım",
    navContact: "İletişim",
    navShopier: "Shopier",
    navShopierStore: "Shopier Mağaza",
    whatsappInfoAria: "WhatsApp'tan bilgi alın",
    heroEyebrow: "Gümüş ve Bakır · Tek Tek El İşi",
    heroTitle: "Elde şekillenen<br>sessiz bir zarafet",
    heroText: "Ozkahya Studio'daki her parça, küçük bir atölyede tek bir çift elden çıkıyor. Kalıp yok, seri üretim yok. Sadece gümüş teller, sabır ve zaman.",
    viewCollection: "Koleksiyonu Gör",
    meetWorkshop: "Atölyeyi Tanı",
    handmade: "%100 el yapımı",
    silverCopper: "Gümüş ve bakır tasarımlar",
    madeToMeasure: "Ölçüye özel üretim",
    heroImageAlt: "Boyunda mor taşlı, püsküllü gümüş kolye",
    workshopSelection: "Atölyeden seçki",
    purpleStoneNecklace: "Mor taşlı gümüş kolye",
    silverHandmade: "Gümüş · El işi",
    selectedPieces: "Seçilmiş Parçalar",
    featured: "Öne çıkanlar",
    viewAll: "Tüm koleksiyonu gör →",
    workshopVisualAria: "Elde örülmüş gümüş bileklikler ve tel detayları",
    wideBraceletAlt: "Geniş örgülü gümüş bilekliğin tamamı ve silindir kapaması",
    wovenDetailAlt: "Gümüş tel örgünün yakın plan detayı",
    wovenByHand: "Tel tel, elde örülür",
    workshopTitle: "Bir masa, incecik teller, çok fazla sabır",
    workshopText: "Ozkahya Studio, İzmir'de bir ev atölyesinde kuruldu. Her tasarım kağıt üzerinde bir çizim olarak başlıyor. Sonra gümüş ve bakır teller elde bükülüyor, örülüyor, lehimleniyor ve tek tek parlatılıyor. Bu yüzden hiçbir parça diğerinin tam kopyası değil. Yüzeydeki her küçük iz elle yapıldığının işareti.",
    design: "Tasarım",
    designText: "Fikir önce eskiz defterinde şekil alır, ölçüleri belirlenir.",
    shaping: "Şekillendirme",
    shapingText: "Gümüş ve bakır teller tek tek kesilir, elde bükülerek form verilir ve lehimlenir.",
    finishing: "Bitirme",
    finishingText: "Zımparalama, parlatma ve varsa doğal taşın yuvasına oturtulması.",
    jewelryCare: "Takı Bakımı",
    careTitle: "Uzun yıllar ilk günkü gibi",
    careText: "Gümüş ve bakır yaşayan metallerdir. Birkaç küçük alışkanlık parlaklığını korur.",
    avoidWater: "Sudan uzak tutun",
    avoidWaterText: "Duş, deniz ve havuzdan önce çıkarın. Parfüm ve krem sonrası takın.",
    storeSafely: "Kutusunda saklayın",
    storeSafelyText: "Havayla teması azalttığı için kapalı kutu veya kilitli poşet en iyisidir.",
    softCloth: "Yumuşak bezle silin",
    softClothText: "Kararma olursa kuru mikrofiber bez yeter. Sert kimyasal kullanmayın.",
    contactTitle: "Bir parça mı beğendiniz?",
    contactText: "Satıştaki ürünlerin sipariş ve ödeme işlemleri yalnızca Shopier üzerinden tamamlanır. WhatsApp'ı ürünler, ölçüler ve farklı taş seçenekleri hakkında bilgi almak için kullanabilirsiniz.",
    whatsappLine: "WhatsApp bilgi hattı",
    phone: "Telefon",
    email: "E-posta",
    customOrder: "Özel sipariş",
    customOrderText: "Aklınızda bir tasarım mı var? Nişan hediyesi, isim harfi, doğum taşı ya da eski bir parçanın yeniden yapımı olabilir. Fotoğrafını gönderin, birlikte çalışalım. Üretim genellikle 1–2 hafta sürüyor. Sipariş hazır olduğunda size özel Shopier ilanı açılır; ödeme yalnızca Shopier'den alınır.",
    whatsappInfo: "WhatsApp'tan bilgi alın",
    sendEmail: "E-posta gönderin",
    copyright: "Ozkahya Studio · Tüm parçalar el yapımıdır.",
    collectionEyebrow: "Koleksiyon",
    collectionHeading: "Atölyeden çıkan tüm parçalar",
    collectionIntro: "Kategoriye göre süzebilir veya arama yapabilirsiniz. Beğendiğiniz parçaya dokunduğunuzda satın alma ve bilgi seçenekleri açılır.",
    searchPlaceholder: "Ürün ara (örn: ametist)",
    searchAria: "Ürün ara",
    orderingEyebrow: "Nasıl sipariş verilir?",
    orderingTitle: "Üç adımda tamamlanır",
    orderingText: "Sipariş ve ödeme güvenli şekilde Shopier üzerinden tamamlanır.",
    orderStep1: "1 · Ürünü seçin",
    orderStep1Text: "Beğendiğiniz parçanın detayını açıp Shopier'de satın al düğmesine dokunun.",
    orderStep2: "2 · Shopier'de ödeyin",
    orderStep2Text: "Sipariş bilgilerinizi girin ve ödemenizi Shopier'in güvenli sayfasında tamamlayın.",
    orderStep3: "3 · Siparişinizi takip edin",
    orderStep3Text: "Hazırlık, kargo ve sipariş takibi Shopier siparişiniz üzerinden yürütülür.",
    openShopier: "Shopier mağazasını aç",
    close: "Kapat",
    buyShopier: "Shopier'de satın al",
    buyShopierArrow: "Shopier'de satın al →",
    whatsappProduct: "WhatsApp'tan bilgi al",
    askByEmail: "E-posta ile sor",
    details: "Detay →",
    soldOut: "Tükendi",
    all: "Tümü",
    piece: "parça",
    pieces: "parça",
    photo: "fotoğraf",
    photos: "fotoğraf",
    noResults: "Bu aramaya uygun bir parça bulunamadı.",
    productDetailsAria: "{name}, detayları gör",
    buyProductAria: "{name} ürününü Shopier'de satın al",
    photoAria: "{number}. fotoğraf",
    statusSoldOut: "Şu an tükendi. Benzeri özel olarak üretilebilir.",
    statusShopier: "Sipariş ve ödeme Shopier üzerinden tamamlanır.",
    statusUnlisted: "Bu parça Shopier'de henüz listelenmedi. Ürün hakkında bilgi alabilirsiniz.",
    waGeneral: "Merhaba, bir ürün hakkında bilgi almak istiyorum.",
    waFallback: "Merhaba, takılarınız hakkında bilgi almak istiyorum.",
    waCustom: "Merhaba, özel sipariş hakkında bilgi almak istiyorum.",
    waProduct: "Merhaba, “{name}” hakkında bilgi almak istiyorum.",
    emailSubject: "{name} hakkında",
  },
  en: {
    homeTitle: "Ozkahya Studio · Handmade Silver and Copper Jewelry",
    homeDescription: "Ozkahya Studio creates handmade silver and copper necklaces, earrings, rings, bracelets, and bangles, one piece at a time.",
    collectionTitle: "Collection · Ozkahya Studio",
    collectionDescription: "Explore Ozkahya Studio's handmade silver and copper necklaces, earrings, rings, bracelets, and bangles.",
    logoAlt: "Handmade Silver and Copper",
    homeAria: "Ozkahya Studio home page",
    menuAria: "Menu",
    languageAria: "Language selection",
    navHome: "Home",
    navCollection: "Collection",
    navWorkshop: "Workshop",
    navCare: "Care",
    navContact: "Contact",
    navShopier: "Shopier",
    navShopierStore: "Shopier Store",
    whatsappInfoAria: "Get information on WhatsApp",
    heroEyebrow: "Silver and Copper · Handmade One by One",
    heroTitle: "Quiet elegance,<br>shaped by hand",
    heroText: "Every Ozkahya Studio piece is made by one pair of hands in a small workshop. No molds, no mass production. Just silver wire, patience, and time.",
    viewCollection: "View the Collection",
    meetWorkshop: "Discover the Workshop",
    handmade: "100% handmade",
    silverCopper: "Silver and copper designs",
    madeToMeasure: "Made to your measurements",
    heroImageAlt: "Purple-stone silver tassel necklace worn around the neck",
    workshopSelection: "Workshop selection",
    purpleStoneNecklace: "Purple-stone silver necklace",
    silverHandmade: "Silver · Handmade",
    selectedPieces: "Selected Pieces",
    featured: "Featured",
    viewAll: "View the full collection →",
    workshopVisualAria: "Handwoven silver bracelets and wire details",
    wideBraceletAlt: "Complete wide woven silver bracelet with cylindrical clasp",
    wovenDetailAlt: "Close-up detail of woven silver wire",
    wovenByHand: "Woven wire by wire",
    workshopTitle: "One table, fine wire, and plenty of patience",
    workshopText: "Ozkahya Studio began in a home workshop in İzmir. Each design starts as a drawing on paper. Silver and copper wires are then bent, woven, soldered, and polished by hand. That is why no two pieces are exact copies. Every small mark on the surface is a sign of the hand that made it.",
    design: "Design",
    designText: "The idea first takes shape in a sketchbook, where its measurements are defined.",
    shaping: "Shaping",
    shapingText: "Silver and copper wires are cut one by one, bent by hand, shaped, and soldered.",
    finishing: "Finishing",
    finishingText: "The piece is sanded and polished, and any natural stone is set into place.",
    jewelryCare: "Jewelry Care",
    careTitle: "Beautiful for years to come",
    careText: "Silver and copper are living metals. A few simple habits will help preserve their shine.",
    avoidWater: "Keep away from water",
    avoidWaterText: "Remove before showering, swimming, or going into the sea. Put it on after perfume and creams.",
    storeSafely: "Store it safely",
    storeSafelyText: "A closed box or sealed pouch is best because it limits contact with air.",
    softCloth: "Wipe with a soft cloth",
    softClothText: "If tarnish appears, a dry microfiber cloth is enough. Avoid harsh chemicals.",
    contactTitle: "Found a piece you love?",
    contactText: "Orders and payments for available pieces are completed only through Shopier. You can use WhatsApp to ask about products, measurements, and different stone options.",
    whatsappLine: "WhatsApp information line",
    phone: "Phone",
    email: "Email",
    customOrder: "Custom orders",
    customOrderText: "Have a design in mind? It could be an engagement gift, an initial, a birthstone, or a remake of an older piece. Send us a photo and we can work on it together. Production usually takes 1–2 weeks. Once your order is ready, a private Shopier listing is created; payment is accepted only through Shopier.",
    whatsappInfo: "Ask on WhatsApp",
    sendEmail: "Send an email",
    copyright: "Ozkahya Studio · Every piece is handmade.",
    collectionEyebrow: "Collection",
    collectionHeading: "Every piece from the workshop",
    collectionIntro: "Filter by category or search the collection. Select a piece to view purchase and contact options.",
    searchPlaceholder: "Search products (e.g. amethyst)",
    searchAria: "Search products",
    orderingEyebrow: "How to order",
    orderingTitle: "Complete your order in three steps",
    orderingText: "Orders and payments are completed securely through Shopier.",
    orderStep1: "1 · Choose your piece",
    orderStep1Text: "Open the piece details and select the Buy on Shopier button.",
    orderStep2: "2 · Pay on Shopier",
    orderStep2Text: "Enter your order details and complete payment on Shopier's secure page.",
    orderStep3: "3 · Track your order",
    orderStep3Text: "Preparation, shipping, and tracking are managed through your Shopier order.",
    openShopier: "Open the Shopier store",
    close: "Close",
    buyShopier: "Buy on Shopier",
    buyShopierArrow: "Buy on Shopier →",
    whatsappProduct: "Ask on WhatsApp",
    askByEmail: "Ask by email",
    details: "Details →",
    soldOut: "Sold out",
    all: "All",
    piece: "piece",
    pieces: "pieces",
    photo: "photo",
    photos: "photos",
    noResults: "No pieces match your search.",
    productDetailsAria: "View details for {name}",
    buyProductAria: "Buy {name} on Shopier",
    photoAria: "Photo {number}",
    statusSoldOut: "Currently sold out. A similar piece can be made to order.",
    statusShopier: "Order and payment are completed through Shopier.",
    statusUnlisted: "This piece is not listed on Shopier yet. Contact us for more information.",
    waGeneral: "Hello, I would like information about a product.",
    waFallback: "Hello, I would like information about your jewelry.",
    waCustom: "Hello, I would like information about a custom order.",
    waProduct: "Hello, I would like information about “{name}”.",
    emailSubject: "About {name}",
  },
};
